// This file was generated by `crates/core/src/bin/generate_types.rs`.

// Do not edit this file manually.

// If you are an AI, and you absolutely have to edit this file, please confirm with the user first.

export type Project = { id: string, name: string, default_agent_working_dir: string | null, remote_project_id: string | null, description: string | null, status: string | null, default_workspace_path: string | null, active_repo_id: string | null, created_at: Date, updated_at: Date, };

export type CreateProject = { name: string, repositories: Array<CreateProjectRepo>, description: string | null, status: string | null, default_workspace_path: string | null, active_repo_id: string | null, };

export type UpdateProject = { name: string | null, description: string | null, status: string | null, default_workspace_path: string | null, active_repo_id: string | null, };

export type SearchResult = { path: string, is_file: boolean, match_type: SearchMatchType, 
/**
 * Ranking score based on git history (higher = more recently/frequently edited)
 */
score: bigint, };

export type SearchMatchType = "FileName" | "DirectoryName" | "FullPath";

export type ProjectMember = { id: string, project_id: string, member_type: ProjectMemberType, user_id: string | null, agent_id: string | null, member_name: string | null, role: string | null, display_order: bigint, default_workspace_path: string | null, allowed_skill_ids: string[], execution_config: MemberExecutionConfig, is_default: boolean, created_at: Date, updated_at: Date, };

export enum ProjectMemberType { human = "human", agent = "agent" }

export type CreateProjectMember = { member_type: ProjectMemberType, user_id: string | null, agent_id: string | null, member_name: string | null, role: string | null, display_order: bigint, default_workspace_path: string | null, allowed_skill_ids: Array<string>, execution_config: MemberExecutionConfig | null, is_default: boolean, };

export type UpdateProjectMember = { member_type: ProjectMemberType | null, user_id: string | null, agent_id: string | null, member_name?: string | null, role: string | null, display_order: bigint | null, default_workspace_path: string | null, allowed_skill_ids: Array<string> | null, execution_config: MemberExecutionConfig | null, is_default: boolean | null, };

export type MemberExecutionConfig = { runner_type?: BaseCodingAgent | null, model_name?: string | null, thinking_effort?: string | null, model_variant?: string | null, };

export type ProjectPath = { id: string, project_id: string, path: string, label: string | null, kind: ProjectPathKind, is_default: boolean, created_at: Date, updated_at: Date, };

export enum ProjectPathKind { workspace = "workspace", artifact = "artifact", external = "external" }

export type CreateProjectPath = { path: string, label: string | null, kind: ProjectPathKind, is_default: boolean, };

export type UpdateProjectPath = { path: string | null, label: string | null, kind: ProjectPathKind | null, is_default: boolean | null, };

export type CreateProjectRepo = { display_name: string, git_repo_path: string, };

export type ProjectStats = { id: string, project_id: string, period_start: string | null, period_end: string | null, feature_count: bigint, bugfix_count: bigint, test_count: bigint, input_tokens: bigint, output_tokens: bigint, cache_read_tokens: bigint, reasoning_output_tokens: bigint, total_tokens: bigint, cost_total: number | null, updated_at: Date, };

export type ProjectDeliveryEvent = { id: string, project_id: string, session_id: string | null, workflow_execution_id: string | null, step_id: string | null, event_type: ProjectDeliveryEventType, title: string | null, source: string | null, created_at: Date, };

export enum ProjectDeliveryEventType { feature = "feature", bugfix = "bugfix", test = "test" }

export type ProjectWorkItem = { id: string, project_id: string, type: ProjectWorkItemType, status: ProjectWorkItemStatus, title: string, description: string | null, labels_json: string | null, priority: ProjectWorkItemPriority, source: ProjectWorkItemSource, created_by: string | null, created_at: Date, updated_at: Date, };

export type CreateProjectWorkItem = { type: ProjectWorkItemType, status?: ProjectWorkItemStatus, title: string, description: string | null, labels_json?: string, priority: ProjectWorkItemPriority, source: ProjectWorkItemSource, created_by: string | null, };

export type UpdateProjectWorkItem = { type: ProjectWorkItemType | null, status: ProjectWorkItemStatus | null, title: string | null, description: string | null, labels_json: string | null, priority: ProjectWorkItemPriority | null, };

export enum ProjectWorkItemType { feature = "feature", bug = "bug", task = "task", deploy = "deploy", test = "test", doc = "doc", refactor = "refactor" }

export enum ProjectWorkItemStatus { open = "open", in_progress = "in_progress", blocked = "blocked", ready_to_merge = "ready_to_merge", merging = "merging", done = "done", cancelled = "cancelled", duplicate = "duplicate" }

export enum ProjectWorkItemPriority { low = "low", medium = "medium", high = "high", urgent = "urgent" }

export enum ProjectWorkItemSource { manual = "manual", github_issue = "github_issue", workflow = "workflow", session = "session" }

export type ProjectWorkItemExternalLink = { id: string, project_work_item_id: string, provider: string, repo_id: string | null, external_type: ProjectExternalType, external_id: string, number: bigint | null, url: string | null, state: string | null, metadata_json: string | null, last_synced_at: Date | null, stale: boolean, created_at: Date, updated_at: Date, };

export type CreateProjectWorkItemExternalLink = { provider: string, repo_id: string | null, external_type: ProjectExternalType, external_id: string, number: bigint | null, url: string | null, state: string | null, metadata_json: string | null, last_synced_at: Date | null, stale: boolean, };

export enum ProjectExternalType { github_issue = "github_issue", github_pr = "github_pr", github_commit = "github_commit", github_deployment = "github_deployment", github_release = "github_release" }

export type ProjectWorkItemExecutionLink = { id: string, project_work_item_id: string, session_id: string | null, workflow_execution_id: string | null, workflow_step_id: string | null, run_id: string | null, link_type: ProjectExecutionLinkType, created_at: Date, };

export type CreateProjectWorkItemExecutionLink = { session_id: string | null, workflow_execution_id: string | null, workflow_step_id: string | null, run_id: string | null, link_type: ProjectExecutionLinkType, };

export enum ProjectExecutionLinkType { created_from = "created_from", discussed_in = "discussed_in", implemented_by = "implemented_by", reviewed_by = "reviewed_by", delivered_by = "delivered_by" }

export type ProjectDeliveryRecord = { id: string, project_work_item_id: string | null, repo_id: string | null, external_link_id: string | null, event_type: ProjectDeliveryEventTypeV2, external_id: string | null, url: string | null, actor: string | null, source_session_id: string | null, source_workflow_execution_id: string | null, metadata_json: string | null, occurred_at: Date, created_at: Date, };

export type CreateProjectDeliveryRecord = { project_work_item_id: string | null, repo_id: string | null, external_link_id: string | null, event_type: ProjectDeliveryEventTypeV2, external_id: string | null, url: string | null, actor: string | null, source_session_id: string | null, source_workflow_execution_id: string | null, metadata_json: string | null, occurred_at: Date | null, };

export enum ProjectDeliveryEventTypeV2 { pr_opened = "pr_opened", pr_merged = "pr_merged", deployment = "deployment", release = "release", test_passed = "test_passed", test_failed = "test_failed", commit_created = "commit_created" }

export type ProjectDeliveryStatsSummary = { period_start: string, period_end: string, pr_opened_count: bigint, pr_merged_count: bigint, deployment_count: bigint, release_count: bigint, test_passed_count: bigint, test_failed_count: bigint, commit_created_count: bigint, };

export type GitHubOperationAudit = { id: string, actor: string | null, operation_source: GitHubOperationSource, session_id: string | null, workflow_execution_id: string | null, repo_id: string | null, target_type: GitHubTargetType, target_id: string | null, action: string, result: GitHubOperationResult, error: string | null, created_at: Date, };

export type CreateGitHubOperationAudit = { actor: string | null, operation_source: GitHubOperationSource, session_id: string | null, workflow_execution_id: string | null, repo_id: string | null, target_type: GitHubTargetType, target_id: string | null, action: string, result: GitHubOperationResult, error: string | null, };

export enum GitHubOperationSource { user_ui = "user_ui", agent = "agent" }

export enum GitHubOperationResult { pending_approval = "pending_approval", approved = "approved", denied = "denied", success = "success", failed = "failed" }

export enum GitHubTargetType { issue = "issue", pull_request = "pull_request", repo = "repo" }

export type GitHubPendingPrCreation = { id: string, project_id: string, repo_integration_id: string, work_item_id: string | null, audit_id: string | null, base_branch: string, head_branch: string, title: string, body: string | null, status: GitHubPendingPrStatus, pull_request_number: bigint | null, pull_request_url: string | null, last_error: string | null, created_at: Date, updated_at: Date, };

export type CreateGitHubPendingPrCreation = { project_id: string, repo_integration_id: string, work_item_id: string | null, audit_id: string | null, base_branch: string, head_branch: string, title: string, body: string | null, status: GitHubPendingPrStatus, pull_request_number: bigint | null, pull_request_url: string | null, last_error: string | null, };

export enum GitHubPendingPrStatus { push_failed = "push_failed", pushed = "pushed", create_failed = "create_failed", local_link_failed = "local_link_failed", completed = "completed" }

export type Repo = { id: string, path: string, name: string, display_name: string, setup_script: string | null, cleanup_script: string | null, archive_script: string | null, copy_files: string | null, parallel_setup_script: boolean, dev_server_script: string | null, default_target_branch: string | null, default_working_dir: string | null, created_at: Date, updated_at: Date, };

export type RepoIntegration = { id: string, repo_id: string, provider: string, owner: string | null, name: string | null, remote_url: string | null, default_branch: string | null, external_id: string | null, installation_id: string | null, github_account_id: string | null, repo_grant_json: string | null, role: RepoIntegrationRole, sync_status: RepoIntegrationSyncStatus, last_synced_at: Date | null, last_error: string | null, created_at: Date, updated_at: Date, };

export type UpdateRepoIntegration = { provider: string | null, owner: string | null, name: string | null, remote_url: string | null, default_branch: string | null, external_id: string | null, installation_id: string | null, github_account_id: string | null, repo_grant_json: string | null, role: RepoIntegrationRole | null, sync_status: RepoIntegrationSyncStatus | null, last_synced_at: Date | null, last_error: string | null, };

export type CreateRepoIntegration = { repo_id: string, provider: string, owner: string | null, name: string | null, remote_url: string | null, default_branch: string | null, external_id: string | null, installation_id: string | null, github_account_id: string | null, repo_grant_json: string | null, role: RepoIntegrationRole | null, sync_status: RepoIntegrationSyncStatus, };

export enum RepoIntegrationSyncStatus { connected = "connected", disconnected = "disconnected", error = "error" }

export enum RepoIntegrationRole { primary = "primary", auxiliary = "auxiliary" }

export type CreateProjectGitHubRepoIntegration = { repo_id?: string, owner?: string, name?: string, full_name?: string, html_url?: string, clone_url?: string, ssh_url?: string, default_branch?: string, external_id?: string, installation_id?: string, github_account_id?: string, repo_grant_json?: JsonValue | null, role?: RepoIntegrationRole, };

export type GitHubPendingOperation = { id: string, project_id: string, repo_integration_id: string, audit_id: string, operation_kind: GitHubPendingOperationKind, target_type: GitHubTargetType, target_id: string | null, payload_json: string, status: GitHubPendingOperationStatus, last_error: string | null, created_at: Date, updated_at: Date, };

export type CreateGitHubPendingOperation = { project_id: string, repo_integration_id: string, audit_id: string, operation_kind: GitHubPendingOperationKind, target_type: GitHubTargetType, target_id: string | null, payload_json: string, };

export enum GitHubPendingOperationKind { issue_comment = "issue_comment", issue_state = "issue_state", issue_labels = "issue_labels", issue_assignees = "issue_assignees" }

export enum GitHubPendingOperationStatus { pending_approval = "pending_approval", completed = "completed", failed = "failed", denied = "denied" }

export type ProjectDetail = { project: Project, paths: Array<ProjectPath>, members: Array<ProjectMember>, sessions: Array<ChatSession>, repos: Array<Repo>, stats: Array<ProjectStats>, };

export type ProjectWorkItemDetail = { work_item: ProjectWorkItem, external_links: Array<ProjectWorkItemExternalLink>, execution_links: Array<ProjectWorkItemExecutionLink>, delivery_records: Array<ProjectDeliveryRecord>, github_audits: Array<GitHubOperationAudit>, github_issue_detail: GitHubIssueDetail | null, };

export type SourceControlFileStatus = "modified" | "added" | "deleted" | "untracked" | "renamed" | "copied" | "type_changed";

export type SourceControlDiffArea = "changes" | "staged";

export type SourceControlOperationInProgress = "merge" | "rebase" | "cherry_pick" | "revert";

export type SourceControlPlainReason = "not_git_repo";

export type SourceControlOperationFailureCode = "path_outside_workspace" | "not_session_scoped" | "shared_file" | "external_staged_conflict" | "stale_status" | "git_operation_blocked" | "file_missing" | "unknown";

export type SourceControlCommitErrorCode = "empty_message" | "empty_staged" | "external_staged_conflict" | "shared_file_requires_confirmation" | "detached_head" | "git_operation_blocked" | "stale_status" | "path_outside_workspace" | "not_session_scoped" | "unknown";

export type SourceControlFile = { path: string, old_path: string | null, status: SourceControlFileStatus, additions: number, deletions: number, has_diff: boolean, is_binary: boolean, is_too_large: boolean, shared: boolean, shared_session_ids: Array<string>, blocked_reason: string | null, };

export type SessionSourceControlStatus = { "mode": "git", workspace_id: string | null, workspace_path: string, branch: string, head_sha: string | null, changes: Array<SourceControlFile>, staged_changes: Array<SourceControlFile>, external_staged_paths: Array<string>, operation_in_progress: SourceControlOperationInProgress | null, detached_head: boolean, blocked_reason: string | null, } | { "mode": "plain", workspace_id: string | null, workspace_path: string, files: Array<SourceControlFile>, reason: SourceControlPlainReason, };

export type SourceControlDiffRequest = { session_id: string, workspace_id?: string | null, path: string, area: SourceControlDiffArea, };

export type SourceControlDiffResponse = { path: string, old_path: string | null, area: SourceControlDiffArea, base_label: string, compare_label: string, unified_diff: string | null, additions: number, deletions: number, is_binary: boolean, is_too_large: boolean, content_omitted: boolean, message: string | null, };

export type SourceControlStageRequest = { session_id: string, workspace_id?: string | null, paths: Array<string>, force_shared?: boolean | null, };

export type SourceControlUnstageRequest = { session_id: string, workspace_id?: string | null, paths: Array<string>, };

export type SourceControlDiscardRequest = { session_id: string, workspace_id?: string | null, paths: Array<string>, force_shared?: boolean | null, expected_head_sha?: string | null, };

export type SourceControlOperationFailure = { path: string, code: SourceControlOperationFailureCode, message: string, };

export type SourceControlOperationResponse = { ok: boolean, succeeded: Array<string>, failed: Array<SourceControlOperationFailure>, status?: SessionSourceControlStatus | null, head_sha?: string | null, operation_id?: string | null, };

export type SourceControlCommitRequest = { session_id: string, workspace_id?: string | null, message: string, expected_staged_paths: Array<string>, force_shared?: boolean | null, work_item_ids?: Array<string>, expected_head_sha?: string | null, };

export type SourceControlCommitResponse = { commit_sha: string, short_sha: string, branch: string, message: string, committed_paths: Array<string>, additions: number, deletions: number, status: SessionSourceControlStatus, };

export type SourceControlCommitError = { code: SourceControlCommitErrorCode, message: string, conflicting_paths?: Array<string>, status?: SessionSourceControlStatus, };

export type GitHubAccount = { login: string, id: bigint, avatar_url: string | null, html_url: string | null, scopes: Array<string>, connected_at: Date, };

export type GitHubDeviceFlowStartResponse = { device_code: string, user_code: string, verification_uri: string, verification_uri_complete: string | null, expires_in: bigint, interval: bigint, };

export type GitHubDeviceFlowPollResponse = { status: GitHubDeviceFlowPollStatus, account: GitHubAccount | null, error: string | null, };

export type GitHubDeviceFlowPollStatus = "pending" | "slow_down" | "authorized" | "denied" | "expired" | "error";

export type GitHubOAuthStartResponse = { flow_id: string, authorization_url: string, expires_at: Date, };

export type GitHubOAuthStatusResponse = { status: GitHubOAuthFlowStatus, account: GitHubAccount | null, error: string | null, };

export type GitHubOAuthFlowStatus = "pending" | "authorized" | "denied" | "expired" | "error";

export type GitHubApiErrorData = { code: string, message: string, retry_after: Date | null, last_synced_at: Date | null, stale: boolean, };

export type GitHubIssueSummary = { number: bigint, node_id: string, title: string, state: string, url: string, author: string | null, author_avatar_url: string | null, labels: Array<string>, assignees: Array<string>, created_at: Date, updated_at: Date, last_synced_at: Date | null, stale: boolean, work_item_id: string | null, };

export type GitHubIssueDetail = { summary: GitHubIssueSummary, body: string | null, comments: Array<GitHubIssueComment>, };

export type GitHubIssueComment = { id: bigint, body: string, author: string | null, author_avatar_url: string | null, created_at: Date, };

export type GitHubPullRequestSummary = { number: bigint, title: string, state: string, url: string, head_branch: string, base_branch: string, };

export type GitHubRepositorySummary = { id: bigint, node_id: string, full_name: string, owner: string, name: string, private: boolean, default_branch: string, html_url: string, clone_url: string, ssh_url: string, updated_at: Date, };

export type CreateGitHubPullRequest = { title: string, body: string | null, head: string, base: string, draft: boolean, };

export type GitHubRepoMetadata = { id: bigint, node_id: string, full_name: string, default_branch: string, html_url: string, };

export type GitHubPrPreviewCommit = { sha: string, subject: string, };

export type GitHubPrPreview = { repo_id: string, base_branch: string, head_branch: string, head_pushed: boolean, commits: Array<GitHubPrPreviewCommit>, diff_summary: string, diff_text: string, requires_push: boolean, };

export type GitHubPrPreviewRequest = { repo_integration_id: string, base_branch: string, head_branch: string, };

export type GitHubCreatePrRequest = { repo_integration_id: string, base_branch: string, head_branch: string, title: string, body: string | null, work_item_id: string | null, operation_source: GitHubOperationSource, };

export type GitHubRetryPrRequest = { pending_pr_id: string, operation_source: GitHubOperationSource, };

export type GitHubCreatePrResponse = { pull_request: GitHubPullRequestSummary | null, delivery_record: ProjectDeliveryRecord | null, external_link: ProjectWorkItemExternalLink | null, audit_id: string, result: GitHubOperationResult, pending_pr: GitHubPendingPrCreation | null, };

export type RepoWithTargetBranch = { target_branch: string, id: string, path: string, name: string, display_name: string, setup_script: string | null, cleanup_script: string | null, archive_script: string | null, copy_files: string | null, parallel_setup_script: boolean, dev_server_script: string | null, default_target_branch: string | null, default_working_dir: string | null, created_at: Date, updated_at: Date, };

export type Tag = { id: string, tag_name: string, content: string, created_at: string, updated_at: string, };

export type CreateTag = { tag_name: string, content: string, };

export type UpdateTag = { tag_name: string | null, content: string | null, };

export type TaskStatus = "todo" | "inprogress" | "inreview" | "done" | "cancelled";

export type Task = { id: string, project_id: string, title: string, description: string | null, status: TaskStatus, parent_workspace_id: string | null, created_at: string, updated_at: string, };

export type TaskWithAttemptStatus = { has_in_progress_attempt: boolean, last_attempt_failed: boolean, executor: string, id: string, project_id: string, title: string, description: string | null, status: TaskStatus, parent_workspace_id: string | null, created_at: string, updated_at: string, };

export type TaskRelationships = { parent_task: Task | null, current_workspace: Workspace, children: Array<Task>, };

export type DraftFollowUpData = { message: string, executor_profile_id: ExecutorProfileId, };

export type DraftWorkspaceData = { message: string, project_id: string | null, repos: Array<DraftWorkspaceRepo>, selected_profile: ExecutorProfileId | null, };

export type DraftWorkspaceRepo = { repo_id: string, target_branch: string, };

export type PreviewSettingsData = { url: string, screen_size: string | null, responsive_width: number | null, responsive_height: number | null, };

export type WorkspaceNotesData = { content: string, };

export type WorkspacePanelStateData = { right_main_panel_mode: string | null, is_left_main_panel_visible: boolean, };

export type UiPreferencesData = { 
/**
 * Preferred repo actions per repo
 */
repo_actions: { [key in string]?: string }, 
/**
 * Expanded/collapsed state for UI sections
 */
expanded: { [key in string]?: boolean }, 
/**
 * Context bar position
 */
context_bar_position: string | null, 
/**
 * Pane sizes
 */
pane_sizes: { [key in string]?: JsonValue }, 
/**
 * Collapsed paths per workspace in file tree
 */
collapsed_paths: { [key in string]?: Array<string> }, 
/**
 * Global left sidebar visibility
 */
is_left_sidebar_visible: boolean | null, 
/**
 * Global right sidebar visibility
 */
is_right_sidebar_visible: boolean | null, 
/**
 * Global terminal visibility
 */
is_terminal_visible: boolean | null, 
/**
 * Workspace-specific panel states
 */
workspace_panel_states: { [key in string]?: WorkspacePanelStateData }, };

export type ScratchPayload = { "type": "DRAFT_TASK", "data": string } | { "type": "DRAFT_FOLLOW_UP", "data": DraftFollowUpData } | { "type": "DRAFT_WORKSPACE", "data": DraftWorkspaceData } | { "type": "PREVIEW_SETTINGS", "data": PreviewSettingsData } | { "type": "WORKSPACE_NOTES", "data": WorkspaceNotesData } | { "type": "UI_PREFERENCES", "data": UiPreferencesData };

export enum ScratchType { DRAFT_TASK = "DRAFT_TASK", DRAFT_FOLLOW_UP = "DRAFT_FOLLOW_UP", DRAFT_WORKSPACE = "DRAFT_WORKSPACE", PREVIEW_SETTINGS = "PREVIEW_SETTINGS", WORKSPACE_NOTES = "WORKSPACE_NOTES", UI_PREFERENCES = "UI_PREFERENCES" }

export type Scratch = { id: string, payload: ScratchPayload, created_at: string, updated_at: string, };

export type CreateScratch = { payload: ScratchPayload, };

export type UpdateScratch = { payload: ScratchPayload, };

export type ChatSession = { id: string, title: string | null, status: ChatSessionStatus, lead_agent_id: string | null, summary_text: string | null, archive_ref: string | null, last_seen_diff_key: string | null, team_protocol: string | null, team_protocol_enabled: boolean, default_workspace_path: string | null, chat_input_mode: string | null, project_id: string | null, created_at: string, updated_at: string, archived_at: string | null, };

export enum ChatSessionStatus { active = "active", archived = "archived" }

export type CreateChatSession = { title: string | null, workspace_path: string | null, project_id: string | null, };

export type UpdateChatSession = { title: string | null, status: ChatSessionStatus | null, lead_agent_id?: string | null, summary_text: string | null, archive_ref: string | null, last_seen_diff_key: string | null, team_protocol: string | null, team_protocol_enabled: boolean | null, default_workspace_path: string | null, chat_input_mode?: string | null, };

export type ChatAgent = { id: string, name: string, runner_type: string, system_prompt: string, tools_enabled: JsonValue, model_name: string | null, owner_project_id: string | null, created_at: string, updated_at: string, };

export type CreateChatAgent = { name: string, runner_type: string, system_prompt: string | null, tools_enabled: JsonValue | null, model_name: string | null, owner_project_id?: string, };

export type UpdateChatAgent = { name: string | null, runner_type: string | null, system_prompt: string | null, tools_enabled: JsonValue | null, model_name: string | null, };

export type ChatMessage = { id: string, session_id: string, sender_type: ChatSenderType, sender_id: string | null, content: string, mentions: string[], meta: JsonValue, created_at: string, };

export enum ChatSenderType { user = "user", agent = "agent", system = "system" }

export type ChatSessionAgent = { id: string, session_id: string, agent_id: string, state: ChatSessionAgentState, workspace_path: string | null, pty_session_key: string | null, agent_session_id: string | null, agent_message_id: string | null, project_member_id: string | null, execution_config: MemberExecutionConfig, allowed_skill_ids: string[], created_at: string, updated_at: string, };

export enum ChatSessionAgentState { idle = "idle", running = "running", stopping = "stopping", waitingapproval = "waitingapproval", dead = "dead" }

export type ChatPermission = { id: string, session_id: string, session_agent_id: string, capability: string, scope: JsonValue, ttl_type: ChatPermissionTtlType, expires_at: string | null, granted_by: string | null, created_at: string, };

export enum ChatPermissionTtlType { once = "once", time = "time", session = "session" }

export type ChatArtifact = { id: string, session_id: string, name: string, path: string, type: string, created_by: string | null, pinned: boolean, created_at: string, };

export type ChatRun = { id: string, session_id: string, session_agent_id: string, workspace_path: string | null, run_index: bigint, run_dir: string, input_path: string | null, output_path: string | null, raw_log_path: string | null, meta_path: string | null, log_state: ChatRunLogState, artifact_state: ChatRunArtifactState, log_truncated: boolean, log_capture_degraded: boolean, pruned_at: string | null, prune_reason: string | null, retention_summary_json: string | null, created_at: string, };

export enum ChatRunLogState { live = "live", tail = "tail", pruned = "pruned" }

export enum ChatRunArtifactState { full = "full", stub = "stub", pruned = "pruned" }

export type ChatRunRetentionSummary = { kind: string | null, finished_at: string | null, error_summary: string | null, error_type: string | null, assistant_excerpt: string | null, total_tokens: number | null, token_usage: TokenUsageInfo | null, workflow_execution_id: string | null, workflow_agent_session_id: string | null, workflow_step_id: string | null, workflow_step_key: string | null, log_bytes_total: bigint | null, log_bytes_persisted: bigint | null, live_bytes_dropped: bigint | null, log_truncated: boolean | null, log_capture_degraded: boolean | null, pruned_at: string | null, prune_reason: string | null, };

export type ChatRunRetentionInfo = { run_id: string, session_agent_id: string, created_at: string, log_state: ChatRunLogState, artifact_state: ChatRunArtifactState, log_truncated: boolean, log_capture_degraded: boolean, pruned_at: string | null, prune_reason: string | null, retention_summary: ChatRunRetentionSummary | null, };

export type WorkflowStepTokenEntry = { session_id: string, session_title: string, workflow_execution_id: string, workflow_step_id: string, workflow_step_key: string, workflow_step_title: string, agent_name: string | null, latest_run_id: string | null, run_count: bigint, input_tokens: bigint, output_tokens: bigint, cache_read_tokens: bigint, reasoning_output_tokens: bigint, total_tokens: bigint, estimated_cost: number, model_id: string | null, model_name: string | null, };

export type WorkflowStepTokensResponse = { steps: Array<WorkflowStepTokenEntry>, };

export type WorkflowStepTokenUsageResponse = { usage: WorkflowStepTokenEntry | null, };

export type ChatWorkItem = { id: string, session_id: string, run_id: string, session_agent_id: string, agent_id: string, item_type: ChatWorkItemType, content: string, created_at: string, };

export enum ChatWorkItemType { artifact = "artifact", conclusion = "conclusion" }

export type ChatSkill = { id: string, name: string, description: string, content: string, trigger_type: string, trigger_keywords: string[], enabled: boolean, source: string, source_url: string | null, version: string, author: string | null, tags: string[], category: string | null, compatible_agents: string[], 
/**
 * Download count from skills.sh registry
 */
download_count: bigint, created_at: string, updated_at: string, };

export type ChatSkillTriggerType = "always" | "keyword" | "manual";

export type CreateChatSkill = { name: string, description: string | null, content: string, trigger_type: string | null, trigger_keywords: Array<string> | null, enabled: boolean | null, source: string | null, source_url: string | null, version: string | null, author: string | null, tags: Array<string> | null, category: string | null, compatible_agents: Array<string> | null, 
/**
 * Download count from skills.sh registry
 */
download_count: bigint | null, };

export type UpdateChatSkill = { name: string | null, description: string | null, content: string | null, trigger_type: string | null, trigger_keywords: Array<string> | null, enabled: boolean | null, source: string | null, source_url: string | null, version: string | null, author: string | null, tags: Array<string> | null, category: string | null, compatible_agents: Array<string> | null, 
/**
 * Download count from skills.sh registry
 */
download_count: bigint | null, };

export type ChatAgentSkill = { id: string, agent_id: string, skill_id: string, enabled: boolean, created_at: string, };

export type AssignSkillToAgent = { agent_id: string, skill_id: string, enabled: boolean | null, };

export type UpdateAgentSkill = { enabled: boolean | null, };

export enum WorkflowPlanStatus { draft = "draft", ready = "ready", superseded = "superseded", cancelled = "cancelled" }

export enum WorkflowValidationStatus { pending = "pending", valid = "valid", invalid = "invalid" }

export enum WorkflowRevisionEditor { lead = "lead", system = "system" }

export enum WorkflowExecutionStatus { pending = "pending", running = "running", failed = "failed", paused = "paused", recompiling = "recompiling", completed = "completed", waiting = "waiting" }

export enum WorkflowRoundStatus { running = "running", waiting_user_acceptance = "waiting_user_acceptance", accepted = "accepted", rejected = "rejected", archived = "archived" }

export enum WorkflowStepType { task = "task", review = "review", result = "result" }

export enum WorkflowStepStatus { pending = "pending", ready = "ready", running = "running", pre_completed = "pre_completed", interrupt_requested = "interrupt_requested", interrupted = "interrupted", waiting_input = "waiting_input", waiting_review = "waiting_review", blocked = "blocked", revising = "revising", completed = "completed", failed = "failed", skipped = "skipped" }

export enum WorkflowLoopStatus { pending = "pending", running = "running", waiting_review = "waiting_review", passed = "passed", rejected = "rejected", waiting_user = "waiting_user", completed = "completed", failed = "failed" }

export enum ReviewVerdict { approved = "approved", rejected = "rejected" }

export enum ReviewerType { lead = "lead", user = "user" }

export enum WorkflowEdgeKind { hard = "hard", soft = "soft" }

export enum WorkflowAgentSessionRole { lead = "lead", worker = "worker", reviewer = "reviewer" }

export enum WorkflowAgentSessionState { idle = "idle", running = "running", interrupt_requested = "interrupt_requested", interrupted = "interrupted", paused = "paused", completed = "completed", failed = "failed", expired = "expired" }

export enum WorkflowEventType { execution_created = "execution_created", execution_running = "execution_running", execution_failed = "execution_failed", execution_completed = "execution_completed", execution_paused = "execution_paused", execution_waiting = "execution_waiting", round_started = "round_started", round_result_ready = "round_result_ready", user_accepted = "user_accepted", user_rejected = "user_rejected", round_archived = "round_archived", plan_revision_created = "plan_revision_created", plan_recompiled = "plan_recompiled", step_status_changed = "step_status_changed", agent_session_state_changed = "agent_session_state_changed", step_lead_review_started = "step_lead_review_started", step_lead_review_passed = "step_lead_review_passed", step_lead_review_rejected = "step_lead_review_rejected", step_user_review_started = "step_user_review_started", step_user_review_passed = "step_user_review_passed", step_user_review_rejected = "step_user_review_rejected", loop_started = "loop_started", loop_retrying = "loop_retrying", loop_passed = "loop_passed", loop_failed = "loop_failed", iteration_feedback_received = "iteration_feedback_received", iteration_new_plan_generated = "iteration_new_plan_generated" }

export type WorkflowPlanJson = { version: string, title: string, goal: string, agents: WorkflowPlanAgents, globals: WorkflowPlanGlobals | null, viewport: WorkflowPlanViewport | null, nodes: Array<WorkflowPlanNode>, edges: Array<WorkflowPlanEdge>, loops: Array<WorkflowLoopDef> | null, policies: WorkflowPlanPolicies | null, };

export type WorkflowPlanAgents = { lead: string, available: Array<string>, };

export type WorkflowPlanGlobals = { interrupt_mode: string, default_retry: number, global_pause_supported: boolean, };

export type WorkflowPlanViewport = { x: number, y: number, zoom: number, };

export type WorkflowPlanNode = { id: string, type: string, position: WorkflowNodePosition, data: WorkflowNodeData, };

export type WorkflowNodePosition = { x: number, y: number, };

export type WorkflowNodeData = { stepType: string, agentId: string | null, title: string, instructions: string, acceptance: Array<string> | null, outputs: Array<string> | null, interruptible: boolean, maxRetry: number | null, status: string | null, loopKey: string | null, reviewScope: Array<string> | null, };

export type WorkflowLoopDef = { loopKey: string, memberSteps: Array<string>, reviewStep: string, maxRetry: number | null, userReviewRequired: boolean | null, };

export type WorkflowPlanEdge = { id: string, source: string, target: string, type: string | null, data: WorkflowEdgeData | null, };

export type WorkflowEdgeData = { kind: string, };

export type WorkflowPlanPolicies = { approval_required_on: Array<string> | null, permission_required_on: Array<string> | null, on_failure: string | null, allow_plan_revision: boolean, };

export type CompiledGraph = { plan_hash: string, compiled_graph_hash: string, steps: Array<CompiledStep>, edges: Array<CompiledEdge>, ready_step_keys: Array<string>, loops: Array<CompiledLoopDef> | null, };

export type CompiledStep = { step_key: string, step_type: WorkflowStepType, title: string, instructions: string, assigned_agent_id: string | null, acceptance: Array<string> | null, outputs: Array<string> | null, interruptible: boolean, max_retry: number, display_order: number, loop_key: string | null, review_scope: Array<string> | null, };

export type CompiledEdge = { edge_id: string, from_step_key: string, to_step_key: string, edge_kind: WorkflowEdgeKind, };

export type CompiledLoopDef = { loop_key: string, member_step_keys: Array<string>, review_step_key: string, review_scope_step_keys: Array<string>, max_retry: number, user_review_required: boolean, };

export type WorkflowLoop = { id: string, execution_id: string, round_id: string, loop_key: string, review_step_id: string, member_step_ids_json: string, status: WorkflowLoopStatus, retry_count: number, max_retry: number, user_review_required: boolean, rejection_reason: string | null, created_at: string, updated_at: string, };

export type CreateWorkflowLoop = { execution_id: string, round_id: string, loop_key: string, review_step_id: string, member_step_ids_json: string, max_retry: number | null, user_review_required: boolean | null, rejection_reason: string | null, };

export type WorkflowStepReview = { id: string, step_id: string, execution_id: string, reviewer_type: ReviewerType, reviewer_id: string | null, verdict: ReviewVerdict, feedback: string, review_round: number, created_at: string, };

export type CreateWorkflowStepReview = { step_id: string, execution_id: string, reviewer_type: ReviewerType, reviewer_id: string | null, verdict: ReviewVerdict, feedback: string, review_round: number | null, };

export type WorkflowIterationFeedback = { id: string, execution_id: string, from_round_id: string, to_round_id: string | null, user_feedback_json: string, current_status_summary: string, new_plan_diff: string | null, created_at: string, };

export type CreateWorkflowIterationFeedback = { execution_id: string, from_round_id: string, to_round_id: string | null, user_feedback_json: string, current_status_summary: string, new_plan_diff: string | null, };

export type RemoteSkillMeta = { id: string, name: string, description: string, category: string | null, version: string, author: string | null, tags: string[], compatible_agents: string[], source_url: string | null, 
/**
 * Download count from skills.sh registry
 */
download_count: bigint | null, };

export type RemoteSkillPackage = { id: string, name: string, description: string, category: string | null, version: string, author: string | null, tags: Array<string>, compatible_agents: Array<string>, source_url: string | null, content: string, 
/**
 * Download count from skills.sh registry
 */
download_count: bigint | null, };

export type SkillCategory = { id: string, name: string, description: string | null, };

export type InstalledNativeSkill = { skill: ChatSkill, enabled: boolean, can_toggle: boolean, native_path: string, config_path: string | null, };

export type AgentRunMode = "auto" | "local" | "disabled";

export type AgentRuntimeConfig = { runner_type: BaseCodingAgent, run_mode: AgentRunMode, env_json: { [key in string]?: string }, executor_options: JsonValue, updated_at: string, };

export type UpdateAgentRuntimeConfig = { run_mode: AgentRunMode | null, env_json: { [key in string]?: string } | null, executor_options: JsonValue | null, };

export type AgentRuntimeEnvSummary = { key: string, value: string, };

export type AgentRuntimeModelSource = "runner" | "profile_fallback" | "none";

export type AgentRuntimeReasoningCapability = { "kind": "effort", options: Array<string>, } | { "kind": "variant", options: Array<string>, };

export type AgentRuntimeStatus = { runner_type: BaseCodingAgent, installed: boolean, executable: boolean, availability: AvailabilityInfo, discovered_models: Array<string>, model_source: AgentRuntimeModelSource, version: string | null, last_checked_at: string | null, last_error: string | null, run_mode: AgentRunMode, env_summary: Array<AgentRuntimeEnvSummary>, executor_options: JsonValue, };

export type AgentRuntimeListResponse = { runners: Array<AgentRuntimeStatus>, };

export type AgentRuntimeRefreshError = { runner_type: BaseCodingAgent, message: string, preserved_models: Array<string>, };

export type AgentRuntimeRefreshResponse = { runners: Array<AgentRuntimeStatus>, errors: Array<AgentRuntimeRefreshError>, };

export type AgentRuntimeDiagnostics = { runner_type: BaseCodingAgent, installed: boolean, executable: boolean, availability: AvailabilityInfo, config_path: string, install_indicator_path: string | null, discovered_models: Array<string>, model_source: AgentRuntimeModelSource, version: string | null, last_checked_at: string | null, last_error: string | null, run_mode: AgentRunMode, env_summary: Array<AgentRuntimeEnvSummary>, executor_options: JsonValue, };

export type ChatStreamEvent = { "type": "message_new", message: ChatMessage, } | { "type": "message_updated", message: ChatMessage, } | { "type": "work_item_new", work_item: ChatWorkItem, } | { "type": "agent_delta", session_id: string, session_agent_id: string, agent_id: string, run_id: string, stream_type: ChatStreamDeltaType, content: string, delta: boolean, is_final: boolean, } | { "type": "agent_run_started", session_id: string, session_agent_id: string, agent_id: string, agent_name: string, run_id: string, 
/**
 * User (or upstream) message whose processing triggered this run.
 */
source_message_id: string, 
/**
 * Frontend-supplied id from the source message meta (`client_message_id`).
 * Lets the frontend correlate this run with its pending placeholder.
 */
client_message_id: string | null, started_at: string | null, } | { "type": "agent_activity_line", line: ChatRunActivityLine, } | { "type": "agent_state", session_agent_id: string, agent_id: string, state: ChatSessionAgentState, 
/**
 * Run that triggered this state change. Run-scoped transitions
 * (running/idle/dead/stopping driven by a concrete run) carry the
 * active run id; states with no associated run (e.g. orphan
 * recovery) leave this `None`.
 */
run_id: string | null, started_at: string | null, } | { "type": "mention_acknowledged", session_id: string, message_id: string, mentioned_agent: string, agent_id: string, status: MentionStatus, } | { "type": "compression_warning", session_id: string, warning: CompressionWarning, } | { "type": "protocol_notice", session_id: string, session_agent_id: string, agent_id: string, run_id: string, agent_name: string, code: ChatProtocolNoticeCode, target: string | null, detail: string | null, output_is_empty: boolean, } | { "type": "mention_error", session_id: string, message_id: string, agent_name: string, agent_id: string | null, reason: string, } | { "type": "workflow_generate_detected", session_id: string, session_agent_id: string, run_id: string, } | { "type": "workflow_plan_preview_ready", session_id: string, plan_id: string, workflow_card_message: ChatMessage, } | { "type": "workflow_execution_updated", session_id: string, execution_id: string, } | { "type": "workflow_graph_updated", session_id: string, execution_id: string, graph_version: string, reason: string, nodes: Array<WorkflowPlanNode>, edges: Array<WorkflowPlanEdge>, changed_step_ids: Array<string>, } | { "type": "workflow_runtime_line", line_id: string, session_id: string, execution_id: string, workflow_agent_session_id: string | null, step_id: string, step_key: string, agent_id: string, agent_name: string, stream_type: ChatStreamDeltaType, content: string, created_at: string, } | { "type": "file_change_refresh", session_id: string, session_agent_id: string, agent_id: string, run_id: string, 
/**
 * Source message whose processing triggered this run.
 */
message_id: string, changed_files: Array<FileChangeEntry>, ts: string, };

export type ChatStreamDeltaType = "assistant" | "thinking" | "error";

export type ChatRunActivityLineType = "thinking" | "tool" | "assistant" | "error";

export type ChatRunActivityLine = { line_id: string, run_id: string, session_id: string, session_agent_id: string, agent_id: string, agent_name: string, sequence: bigint, line_type: ChatRunActivityLineType, stream_type: ChatStreamDeltaType, content: string, created_at: string, };

export type ChatProtocolNoticeCode = "invalid_json" | "not_json_array" | "empty_message" | "missing_send_target" | "invalid_send_target" | "invalid_send_intent";

export type MentionStatus = "received" | "running" | "completed" | "failed";

export type CompressionWarning = { code: string, message: string, split_file_path: string, };

export type FileChangeType = "created" | "modified" | "deleted";

export type FileChangeEntry = { 
/**
 * Workspace-relative path (forward slashes).
 */
path: string, change_type: FileChangeType, };

export type Image = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type CreateImage = { file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, };

export type Workspace = { id: string, task_id: string, container_ref: string | null, branch: string, agent_working_dir: string | null, setup_completed_at: string | null, created_at: string, updated_at: string, archived: boolean, pinned: boolean, name: string | null, };

export type Session = { id: string, workspace_id: string, executor: string | null, created_at: string, updated_at: string, };

export type ExecutionProcess = { id: string, session_id: string, run_reason: ExecutionProcessRunReason, executor_action: ExecutorAction, status: ExecutionProcessStatus, exit_code: bigint | null, 
/**
 * dropped: true if this process is excluded from the current
 * history view (due to restore/trimming). Hidden from logs/timeline;
 * still listed in the Processes tab.
 */
dropped: boolean, started_at: string, completed_at: string | null, created_at: string, updated_at: string, };

export enum ExecutionProcessStatus { running = "running", completed = "completed", failed = "failed", killed = "killed" }

export type ExecutionProcessRunReason = "setupscript" | "cleanupscript" | "archivescript" | "codingagent" | "devserver";

export type ExecutionProcessRepoState = { id: string, execution_process_id: string, repo_id: string, before_head_commit: string | null, after_head_commit: string | null, merge_commit: string | null, created_at: Date, updated_at: Date, };

export type Merge = { "type": "direct" } & DirectMerge | { "type": "pr" } & PrMerge;

export type DirectMerge = { id: string, workspace_id: string, repo_id: string, merge_commit: string, target_branch_name: string, created_at: string, };

export type PrMerge = { id: string, workspace_id: string, repo_id: string, created_at: string, target_branch_name: string, pr_info: PullRequestInfo, };

export type MergeStatus = "open" | "merged" | "closed" | "unknown";

export type PullRequestInfo = { number: bigint, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, };

export type ApprovalStatus = { "status": "pending" } | { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "timed_out" };

export type CreateApprovalRequest = { tool_name: string, tool_input: JsonValue, tool_call_id: string, };

export type ApprovalResponse = { execution_process_id: string, status: ApprovalStatus, };

export type Diff = { change: DiffChangeKind, oldPath: string | null, newPath: string | null, oldContent: string | null, newContent: string | null, 
/**
 * True when file contents are intentionally omitted (e.g., too large)
 */
contentOmitted: boolean, 
/**
 * Optional precomputed stats for omitted content
 */
additions: number | null, deletions: number | null, repoId: string | null, };

export type DiffChangeKind = "added" | "deleted" | "modified" | "renamed" | "copied" | "permissionChange";

export type ApiResponse<T, E = T> = { success: boolean, data: T | null, error_data: E | null, message: string | null, };

export type LoginStatus = { "status": "loggedout" } | { "status": "loggedin", profile: ProfileResponse, };

export type ProfileResponse = { user_id: string, username: string | null, email: string, providers: Array<ProviderProfile>, };

export type ProviderProfile = { provider: string, username: string | null, display_name: string | null, email: string | null, avatar_url: string | null, };

export type TagSearchParams = { search: string | null, };

export type UserSystemInfo = { config: Config, analytics_user_id: string, deploy_mode: string, login_status: LoginStatus, home_directory: string, environment: Environment, 
/**
 * Capabilities supported per executor (e.g., { "CLAUDE_CODE": ["SESSION_FORK"] })
 */
capabilities: { [key in string]?: Array<BaseAgentCapability> }, executors: { [key in BaseCodingAgent]?: ExecutorConfig }, };

export type Environment = { os_type: string, os_version: string, os_architecture: string, bitness: string, };

export type McpServerQuery = { executor: BaseCodingAgent, };

export type UpdateMcpServersBody = { servers: { [key in string]?: JsonValue }, };

export type GetMcpServerResponse = { mcp_config: McpConfig, config_path: string, };

export type CheckEditorAvailabilityQuery = { editor_type: EditorType, };

export type CheckEditorAvailabilityResponse = { available: boolean, };

export type CheckAgentAvailabilityQuery = { executor: BaseCodingAgent, };

export type ProviderInfo = { id: string, name: string, configured: boolean, };

export type ModelInfo = { id: string, name: string, };

export type ValidateProviderRequest = { api_key: string | null, endpoint: string | null, };

export type ValidateProviderResponse = { valid: boolean, message: string, };

export type ChatSessionListQuery = { status: ChatSessionStatus | null, project_id: string | null, };

export type CreateChatSessionAgentRequest = { agent_id: string, workspace_path: string | null, allowed_skill_ids: Array<string> | null, };

export type UpdateChatSessionAgentRequest = { workspace_path: string | null, allowed_skill_ids: Array<string> | null, };

export type SessionWorkspace = { workspace_path: string, agent_ids: Array<string>, agent_names: Array<string>, is_git_repo: boolean, };

export type SessionWorkspacesResponse = { workspaces: Array<SessionWorkspace>, };

export type SessionWorkspaceChangesQuery = { path: string, include_diff: boolean | null, };

export type WorkspaceChangedFile = { path: string, additions: number, deletions: number, unified_diff: string | null, 
/**
 * Whether a diff can be generated for this file (false for files in .gitignore'd directories).
 */
has_diff: boolean, };

export type WorkspacePathEntry = { path: string, };

export type WorkspaceChanges = { modified: Array<WorkspaceChangedFile>, added: Array<WorkspaceChangedFile>, deleted: Array<WorkspacePathEntry>, untracked: Array<WorkspaceChangedFile>, };

export type WorkspaceChangesResponse = { workspace_path: string, is_git_repo: boolean, changes: WorkspaceChanges | null, error: string | null, };

export type ChatRunRetentionListQuery = { run_ids: string | null, limit: number | null, };

export type ChatRunRetentionListResponse = { runs: Array<ChatRunRetentionInfo>, };

export type ChatRunActivityResponse = { run_id: string, lines: Array<ChatRunActivityLine>, next_offset: bigint | null, is_pruned: boolean, };

export type ChatRunFilesQuery = { 
/**
 * When true, include the per-file unified diff text for each changed file.
 * Defaults to false (paths + counts only) to keep the response light.
 */
include_diff: boolean | null, };

export type ChatRunFilesResponse = { run_id: string, workspace_path: string | null, is_git_repo: boolean, changes: WorkspaceChanges, error: string | null, };

export type UpdateNativeSkillRequest = { enabled: boolean, };

export type ExecutePlanReviewOverride = { stepId: string, leadReview: boolean | null, userReview: boolean | null, };

export type ExecutePlanRequest = { plan: WorkflowPlanJson | null, stepReviewOverrides: Array<ExecutePlanReviewOverride>, };

export type ExecutePlanResponse = { execution_id: string, };

export type ChatMessageListQuery = { limit: bigint | null, };

export type ChatWorkItemListQuery = { limit: bigint | null, };

export type CreateChatMessageRequest = { sender_type: ChatSenderType, sender_id: string | null, content: string, meta: JsonValue | null, };

export type UserReviewResponseRequest = { review_id: string, action: string, feedback: string | null, expected_step_id: string | null, };

export type UserReviewResponseResponse = { execution_id: string, transcript_id: string, status: string, };

export type UserIterationFeedbackDetailRequest = { what_wrong: string, expected: string, priority: string, additional_notes: string | null, };

export type UserIterationFeedbackRequest = { execution_id: string, action: string, feedback: UserIterationFeedbackDetailRequest | null, };

export type UserIterationFeedbackResponse = { execution_id: string, status: string, current_round: number, };

export type CreateProjectRequest = { name: string, repositories: Array<CreateProjectRepo>, description: string | null, status: string | null, default_workspace_path: string | null, active_repo_id: string | null, };

export type AddProjectMemberRequest = { member_type: ProjectMemberType, user_id: string | null, agent_id: string | null, member_name: string | null, role: string | null, display_order: bigint, default_workspace_path: string | null, allowed_skill_ids: Array<string>, execution_config: MemberExecutionConfig, is_default: boolean, };

export type UpdateProjectMemberRequest = { member_name?: string | null, role: string | null, display_order: bigint | null, default_workspace_path: string | null, is_default: boolean | null, allowed_skill_ids: Array<string> | null, execution_config: MemberExecutionConfig | null, };

export type CreateProjectSessionRequest = { title: string | null, workspace_path: string | null, };

export type ProjectStatsQuery = { period_start: string | null, period_end: string | null, };

export type ProjectListResponse = { projects: Array<Project>, };

export type ProjectResponse = { project: Project, };

export type ProjectDetailResponse = { project: Project, paths: Array<ProjectPath>, members: Array<ProjectMember>, sessions: Array<ChatSession>, repos: Array<Repo>, stats: Array<ProjectStats>, };

export type ProjectMemberWithRuntime = { reasoning_capability: AgentRuntimeReasoningCapability | null, id: string, project_id: string, member_type: ProjectMemberType, user_id: string | null, agent_id: string | null, member_name: string | null, role: string | null, display_order: bigint, default_workspace_path: string | null, allowed_skill_ids: string[], execution_config: MemberExecutionConfig, is_default: boolean, created_at: Date, updated_at: Date, };

export type ProjectMembersResponse = { members: Array<ProjectMemberWithRuntime>, };

export type ProjectMemberResponse = { member: ProjectMemberWithRuntime, };

export type ProjectSessionsResponse = { sessions: Array<ChatSession>, };

export type ProjectSessionResponse = { session: ChatSession, };

export type ProjectReposResponse = { repos: Array<Repo>, };

export type ProjectStatsResponse = { stats: Array<ProjectStats>, };

export type SessionSourceControlStatusQuery = { session_id: string, workspace_id?: string | null, };

export type GitHubDevicePollRequest = { device_code: string, };

export type GitHubOAuthStatusQuery = { flow_id: string, };

export type IssueIntegrationProvider = { id: string, name: string, supported: boolean, status: string, };

export type ProjectIssueIntegrationsResponse = { providers: Array<IssueIntegrationProvider>, github_account: GitHubAccount | null, github_repositories: Array<GitHubRepositorySummary>, linked_repositories: Array<RepoIntegration>, primary_repository: RepoIntegration | null, };

export type GitHubIssueQuery = { repo_integration_id: string, q: string | null, };

export type ImportGitHubIssueRequest = { repo_integration_id: string, number: bigint, };

export type DeliveryRecordsQuery = { work_item_id: string | null, repo_id: string | null, };

export type DeliveryStatsQuery = { period_start: string, period_end: string, };

export type IssueCommentRequest = { body: string, operation_source: GitHubOperationSource, };

export type IssueBodyRequest = { body: string, operation_source: GitHubOperationSource, };

export type IssueStateRequest = { state: string, operation_source: GitHubOperationSource, };

export type IssueLabelsRequest = { labels: Array<string>, operation_source: GitHubOperationSource, };

export type IssueAssigneesRequest = { assignees: Array<string>, operation_source: GitHubOperationSource, };

export type PushBranchRequest = { repo_integration_id: string, head_branch: string, base_branch: string | null, title: string | null, body: string | null, work_item_id: string | null, operation_source: GitHubOperationSource, };

export type BranchListQuery = { repo_integration_id: string, };

export type DenyGitHubOperationRequest = { reason: string | null, };

export type ImageResponse = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type ImageMetadata = { exists: boolean, file_name: string | null, path: string | null, size_bytes: bigint | null, format: string | null, proxy_url: string | null, };

export type UnifiedPrComment = { "comment_type": "general", id: string, author: string, author_association: string | null, body: string, created_at: string, url: string | null, } | { "comment_type": "review", id: bigint, author: string, author_association: string | null, body: string, created_at: string, url: string | null, path: string, line: bigint | null, side: string | null, diff_hunk: string | null, };

export type ProviderKind = "git_hub" | "azure_dev_ops" | "unknown";

export type OpenPrInfo = { number: bigint, url: string, title: string, head_branch: string, base_branch: string, };

export type GitRemote = { name: string, url: string, };

export type DirectoryEntry = { name: string, path: string, is_directory: boolean, is_git_repo: boolean, last_modified: bigint | null, };

export type DirectoryListResponse = { entries: Array<DirectoryEntry>, current_path: string, };

export type SearchMode = "taskform" | "settings";

export type WorkflowCardAgent = { session_agent_id: string, workflow_agent_session_id: string | null, agent_id: string, name: string, };

export type WorkflowCardState = "preview_ready" | "preview_invalid" | "pending" | "running" | "waiting" | "paused" | "completed" | "failed";

export type WorkflowCardReview = { reviewer_type: string, verdict: string, feedback: string, review_round: number, created_at: string, };

export type WorkflowCardLoop = { id: string, loop_key: string, status: string, retry_count: number, max_retry: number, user_review_required: boolean, rejection_reason: string | null, member_step_ids: Array<string>, review_step_id: string, };

export type WorkflowReviewField = { key: string, label: string, field_type: string, required: boolean, placeholder: string | null, options: Array<string> | null, };

export type WorkflowReviewAction = { action: string, label: string, style: string, requires_feedback: boolean, };

export type WorkflowReviewPromptTemplate = { message: string, fields: Array<WorkflowReviewField>, actions: Array<WorkflowReviewAction>, };

export type WorkflowPendingReview = { review_id: string, review_type: string, target_id: string, target_title: string, context_summary: string, prompt_template: WorkflowReviewPromptTemplate, };

export type WorkflowPendingInput = { input_id: string, step_id: string, step_key: string, target_title: string, prompt: string, description: string | null, placeholder: string | null, };

export type WorkflowIterationSummary = { round_index: number, status: string, user_feedback: string | null, result_summary: string | null, started_at: string, completed_at: string | null, };

export type WorkflowRoundGraph = { round_id: string, round_index: number, revision_id: string, status: string, plan: WorkflowPlanJson, steps: Array<WorkflowCardStep>, loops: Array<WorkflowCardLoop>, };

export type WorkflowCardStep = { id: string, step_key: string, title: string, step_type: string, status: string, review_phase: string | null, lead_review_required: boolean, user_review_required: boolean, retry_count: number, max_retry: number, loop_key: string | null, latest_review: WorkflowCardReview | null, agent_name: string | null, summary_text: string | null, content: string | null, };

export type WorkflowCardProjection = { execution_id: string | null, plan_id: string, revision_id: string, title: string, goal: string, state: WorkflowCardState, execution_status: string, error_message: string | null, completed_step_count: number, total_step_count: number, result_summary: string | null, outputs: Array<string>, agents: Array<WorkflowCardAgent>, steps: Array<WorkflowCardStep>, current_round: number, loops: Array<WorkflowCardLoop>, pending_review: WorkflowPendingReview | null, pending_reviews: Array<WorkflowPendingReview>, pending_input: WorkflowPendingInput | null, iteration_history: Array<WorkflowIterationSummary>, round_graphs: Array<WorkflowRoundGraph>, plan: WorkflowPlanJson, started_at: string | null, completed_at: string | null, validation_errors: string | null, is_terminal: boolean, has_transcripts: boolean | null, };

export type UserIterationFeedbackDetail = { what_wrong: string, expected: string, priority: string | null, additional_notes: string | null, };

export type UserIterationFeedback = { execution_id: string, round_id: string, action: string, feedback: UserIterationFeedbackDetail | null, };

export type Config = { config_version: string, theme: ThemeMode, executor_profile: ExecutorProfileId, disclaimer_acknowledged: boolean, onboarding_acknowledged: boolean, notifications: NotificationConfig, editor: EditorConfig, github: GitHubConfig, analytics_enabled: boolean, workspace_dir: string | null, last_app_version: string | null, show_release_notes: boolean, language: UiLanguage, git_branch_prefix: string, showcases: ShowcaseState, pr_auto_description_enabled: boolean, pr_auto_description_prompt: string | null, beta_workspaces: boolean, beta_workspaces_invitation_sent: boolean, commit_reminder_enabled: boolean, commit_reminder_prompt: string | null, send_message_shortcut: SendMessageShortcut, 
/**
 * Chat presets configuration (member and team templates)
 */
chat_presets: ChatPresetsConfig, 
/**
 * Global chat bubble font size preference
 */
chat_bubble_font_size: ChatBubbleFontSize, 
/**
 * Chat compression configuration
 */
chat_compression: ChatCompressionConfig, max_agent_chain_depth: number, };

export type NotificationConfig = { sound_enabled: boolean, push_enabled: boolean, sound_file: SoundFile, };

export enum ThemeMode { LIGHT = "LIGHT", DARK = "DARK", SYSTEM = "SYSTEM" }

export type EditorConfig = { editor_type: EditorType, custom_command: string | null, remote_ssh_host: string | null, remote_ssh_user: string | null, };

export enum EditorType { VS_CODE = "VS_CODE", VS_CODE_INSIDERS = "VS_CODE_INSIDERS", CURSOR = "CURSOR", WINDSURF = "WINDSURF", INTELLI_J = "INTELLI_J", ZED = "ZED", XCODE = "XCODE", GOOGLE_ANTIGRAVITY = "GOOGLE_ANTIGRAVITY", CUSTOM = "CUSTOM" }

export type EditorOpenError = { "type": "executable_not_found", executable: string, editor_type: EditorType, } | { "type": "invalid_command", details: string, editor_type: EditorType, } | { "type": "launch_failed", executable: string, details: string, editor_type: EditorType, };

export type GitHubConfig = { pat: string | null, oauth_token: string | null, username: string | null, primary_email: string | null, default_pr_base: string | null, };

export enum SoundFile { ABSTRACT_SOUND1 = "ABSTRACT_SOUND1", ABSTRACT_SOUND2 = "ABSTRACT_SOUND2", ABSTRACT_SOUND3 = "ABSTRACT_SOUND3", ABSTRACT_SOUND4 = "ABSTRACT_SOUND4", COW_MOOING = "COW_MOOING", PHONE_VIBRATION = "PHONE_VIBRATION", ROOSTER = "ROOSTER" }

export type UiLanguage = "BROWSER" | "EN" | "FR" | "JA" | "ES" | "KO" | "ZH_HANS" | "ZH_HANT";

export type ShowcaseState = { seen_features: Array<string>, };

export type SendMessageShortcut = "ModifierEnter" | "Enter";

export enum ChatBubbleFontSize { px12 = "px12", px13 = "px13", px14 = "px14", px15 = "px15", px16 = "px16", px18 = "px18" }

export type ChatCompressionConfig = { 
/**
 * Token threshold before compression kicks in (default: 5000000)
 */
token_threshold: number, 
/**
 * Percentage of messages to compress (default: 25)
 */
compression_percentage: number, };

export type ChatPresetsConfig = { 
/**
 * List of member preset templates
 */
members: Array<ChatMemberPreset>, 
/**
 * List of team preset templates
 */
teams: Array<ChatTeamPreset>, 
/**
 * Team collaboration protocol content; empty string disables injection
 */
team_protocol: string | null, };

export type ChatMemberPreset = { 
/**
 * Unique identifier for the preset
 */
id: string, 
/**
 * Display name (also used as @mention handle)
 */
name: string, 
/**
 * Description of the preset's purpose
 */
description: string, 
/**
 * Optional runner type (null means use default)
 */
runner_type: string | null, 
/**
 * Optional recommended model identifier for the selected runner
 */
recommended_model: string | null, 
/**
 * System prompt defining the agent's behavior
 */
system_prompt: string, 
/**
 * Optional default workspace path
 */
default_workspace_path: string | null, 
/**
 * Skills preselected for members created from this preset
 */
selected_skill_ids: Array<string>, 
/**
 * Tools enabled for this preset
 */
tools_enabled: JsonValue, 
/**
 * Whether this is a built-in preset (cannot be deleted)
 */
is_builtin: boolean, 
/**
 * Whether this preset is enabled (visible for import)
 */
enabled: boolean, };

export type ChatTeamPreset = { 
/**
 * Unique identifier for the preset
 */
id: string, 
/**
 * Display name of the team
 */
name: string, 
/**
 * Description of the team's purpose
 */
description: string, 
/**
 * List of member preset IDs to include in this team
 */
member_ids: Array<string>, 
/**
 * Optional ID of the lead member preset (references a member in member_ids)
 */
lead_member_id?: string | null, 
/**
 * Optional team protocol injected when importing this team preset
 */
team_protocol: string, 
/**
 * Whether this is a built-in preset (cannot be deleted)
 */
is_builtin: boolean, 
/**
 * Whether this preset is enabled (visible for import)
 */
enabled: boolean, };

export type CliConfig = { provider: ProviderConfig, model: ModelConfig, behavior: BehaviorConfig, };

export type ProviderConfig = { 
/**
 * Default provider name: anthropic, openai, google, openrouter, minimax, ollama, custom
 */
default: string, anthropic: ProviderCredentials | null, openai: ProviderCredentials | null, google: ProviderCredentials | null, openrouter: ProviderCredentials | null, minimax: ProviderCredentials | null, ollama: OllamaConfig | null, custom: CustomProviderConfig | null, 
/**
 * 多自定义 Provider 配置
 */
custom_providers?: { [key in string]?: CustomProviderEntry } | null, };

export type ProviderCredentials = { api_key: string | null, endpoint: string | null, };

export type OllamaConfig = { endpoint: string | null, };

export type CustomProviderConfig = { name: string | null, endpoint: string | null, api_key: string | null, };

export type CustomProviderEntry = { 
/**
 * 唯一标识，如 "bailian-coding-plan"
 */
id: string, 
/**
 * 显示名称
 */
name: string | null, 
/**
 * NPM 包名，默认 "@ai-sdk/anthropic"
 */
npm: string | null, 
/**
 * Provider 连接选项
 */
options: CustomProviderOptions, 
/**
 * 模型配置
 */
models: { [key in string]?: CustomModelConfig } | null, };

export type CustomProviderOptions = { baseURL: string | null, api_key: string | null, timeout: bigint | null, };

export type CustomModelConfig = { name: string | null, modalities: ModelModalities | null, options: JsonValue | null, limit: ModelLimits | null, };

export type ModelConfig = { 
/**
 * Default model name
 */
default: string, anthropic: ProviderModelConfig | null, openai: ProviderModelConfig | null, google: ProviderModelConfig | null, };

export type ProviderModelConfig = { default: string | null, };

export type BehaviorConfig = { auto_approve: boolean, auto_compact: boolean, };

export type OpenTeamsCliConfig = { 
/**
 * Provider configurations
 */
provider: { [key in string]?: OpenTeamsCliProviderConfig } | null, 
/**
 * Default model in provider/model format
 */
model: string | null, 
/**
 * Small model for tasks like title generation
 */
small_model: string | null, 
/**
 * Agent configurations
 */
agent: JsonValue | null, 
/**
 * Custom commands
 */
command: JsonValue | null, 
/**
 * MCP server configurations
 */
mcp: JsonValue | null, 
/**
 * Permission settings
 */
permission: JsonValue | null, 
/**
 * LSP server configurations
 */
lsp: JsonValue | null, 
/**
 * Formatter configurations
 */
formatter: JsonValue | null, 
/**
 * Experimental features
 */
experimental: JsonValue | null, 
/**
 * Username to display
 */
username: string | null, 
/**
 * Log level
 */
log_level: string | null, };

export type OpenTeamsCliProviderConfig = { 
/**
 * NPM package for the provider (e.g., "@ai-sdk/anthropic")
 */
npm: string | null, 
/**
 * Display name for the provider
 */
name: string | null, 
/**
 * Provider options (apiKey, baseURL, etc.)
 */
options: OpenTeamsCliProviderOptions | null, 
/**
 * Model configurations
 */
models: { [key in string]?: OpenTeamsCliModelConfig } | null, 
/**
 * Whitelist of model IDs
 */
whitelist: Array<string> | null, 
/**
 * Blacklist of model IDs
 */
blacklist: Array<string> | null, };

export type OpenTeamsCliProviderOptions = { 
/**
 * API key for the provider
 */
apiKey: string | null, 
/**
 * Base URL for the provider API
 */
baseURL: string | null, 
/**
 * Request timeout in milliseconds
 */
timeout: bigint | null, 
/**
 * Chunk timeout in milliseconds
 */
chunkTimeout: bigint | null, 
/**
 * GitHub Enterprise URL for copilot authentication
 */
enterpriseUrl: string | null, 
/**
 * Enable promptCacheKey for this provider
 */
setCacheKey: boolean | null, };

export type OpenTeamsCliModelConfig = { 
/**
 * Display name for the model
 */
name: string | null, 
/**
 * Model modalities (input/output capabilities)
 */
modalities: ModelModalities | null, 
/**
 * Model-specific options
 */
options: JsonValue | null, 
/**
 * Model limits (context window, output tokens)
 */
limit: ModelLimits | null, 
/**
 * Variant-specific configuration
 */
variants: { [key in string]?: ModelVariantConfig } | null, };

export type ModelModalities = { input: Array<string> | null, output: Array<string> | null, };

export type ModelLimits = { context: bigint | null, output: bigint | null, };

export type ModelVariantConfig = { disabled: boolean | null, };

export type SyncToCliRequest = { custom_provider_id: string | null, };

export type SyncToCliResponse = { synced: boolean, message: string, config_path: string | null, };

export type RestartCliResponse = { restarted: boolean, message: string, base_url: string | null, port: number | null, };

export type CustomProviderProbeRequest = { id: string, npm: string | null, options: CustomProviderOptions, model_id: string | null, };

export type CustomProviderProbeStatus = "success" | "failed" | "unsupported";

export type CustomProviderProbeResponse = { status: CustomProviderProbeStatus, valid: boolean, message: string, models: Array<ModelInfo>, };

export type TeamProtocolConfig = { content: string, enabled: boolean, };

export type CreatePresetSnapshotRequest = { team_preset_id: string | null, name: string | null, description: string | null, overwrite_strategy: PresetSnapshotOverwriteStrategy | null, };

export type PresetSnapshotOverwriteStrategy = "fail_if_exists" | "overwrite_custom";

export type CreatePresetSnapshotResponse = { team: ChatTeamPreset, members: Array<ChatMemberPreset>, overwritten: boolean, };

export type GitBranch = { name: string, is_current: boolean, is_remote: boolean, last_commit_date: Date, };

export type QueuedMessage = { 
/**
 * The session this message is queued for
 */
session_id: string, 
/**
 * The follow-up data (message + variant)
 */
data: DraftFollowUpData, 
/**
 * Timestamp when the message was queued
 */
queued_at: string, };

export type QueueStatus = { "status": "empty" } | { "status": "queued", message: QueuedMessage, };

export type ConflictOp = "rebase" | "merge" | "cherry_pick" | "revert";

export type ExecutorAction = { typ: ExecutorActionType, next_action: ExecutorAction | null, };

export type McpConfig = { servers: { [key in string]?: JsonValue }, servers_path: Array<string>, template: JsonValue, preconfigured: JsonValue, is_toml_config: boolean, };

export type ExecutorActionType = { "type": "CodingAgentInitialRequest" } & CodingAgentInitialRequest | { "type": "CodingAgentFollowUpRequest" } & CodingAgentFollowUpRequest | { "type": "ScriptRequest" } & ScriptRequest | { "type": "ReviewRequest" } & ReviewRequest;

export type ScriptContext = "SetupScript" | "CleanupScript" | "ArchiveScript" | "DevServer" | "ToolInstallScript";

export type ScriptRequest = { script: string, language: ScriptRequestLanguage, context: ScriptContext, working_dir: string | null, };

export type ScriptRequestLanguage = "Bash";

export enum BaseCodingAgent { CLAUDE_CODE = "CLAUDE_CODE", AMP = "AMP", GEMINI = "GEMINI", CODEX = "CODEX", OPENCODE = "OPENCODE", OPEN_TEAMS_CLI = "OPEN_TEAMS_CLI", CURSOR_AGENT = "CURSOR_AGENT", QWEN_CODE = "QWEN_CODE", COPILOT = "COPILOT", DROID = "DROID", KIMI_CODE = "KIMI_CODE" }

export type CodingAgent = { "CLAUDE_CODE": ClaudeCode } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OPENCODE": Opencode } | { "OPEN_TEAMS_CLI": OpenTeamsCli } | { "CURSOR_AGENT": CursorAgent } | { "QWEN_CODE": QwenCode } | { "COPILOT": Copilot } | { "DROID": Droid } | { "KIMI_CODE": KimiCode };

export type SlashCommandDescription = { 
/**
 * Command name without the leading slash, e.g. `help` for `/help`.
 */
name: string, description?: string | null, };

export type AvailabilityInfo = { "type": "LOGIN_DETECTED", last_auth_timestamp: bigint, } | { "type": "INSTALLATION_FOUND" } | { "type": "NOT_FOUND" };

export type CommandBuilder = { 
/**
 * Base executable command (e.g., "npx -y @anthropic-ai/claude-code@2.1.161")
 */
base: string, 
/**
 * Optional parameters to append to the base command
 */
params: Array<string> | null, };

export type ExecutorProfileId = { 
/**
 * The executor type (e.g., "CLAUDE_CODE", "AMP")
 */
executor: BaseCodingAgent, 
/**
 * Optional variant name (e.g., "PLAN", "ROUTER")
 */
variant: string | null, };

export type ExecutorConfig = { [key in string]?: { "CLAUDE_CODE": ClaudeCode } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OPENCODE": Opencode } | { "OPEN_TEAMS_CLI": OpenTeamsCli } | { "CURSOR_AGENT": CursorAgent } | { "QWEN_CODE": QwenCode } | { "COPILOT": Copilot } | { "DROID": Droid } | { "KIMI_CODE": KimiCode } };

export type ExecutorConfigs = { executors: { [key in BaseCodingAgent]?: ExecutorConfig }, };

export enum BaseAgentCapability { SESSION_FORK = "SESSION_FORK", SETUP_HELPER = "SETUP_HELPER", CONTEXT_USAGE = "CONTEXT_USAGE" }

export type ClaudeCode = { append_prompt: AppendPrompt, claude_code_router?: boolean | null, plan?: boolean | null, approvals?: boolean | null, model?: string | null, effort?: string | null, dangerously_skip_permissions?: boolean | null, disable_api_key?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Gemini = { append_prompt: AppendPrompt, model?: string | null, thinking_effort?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Amp = { append_prompt: AppendPrompt, model?: string | null, dangerously_allow_all?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Codex = { append_prompt: AppendPrompt, sandbox?: SandboxMode | null, ask_for_approval?: AskForApproval | null, oss?: boolean | null, model?: string | null, model_reasoning_effort?: ReasoningEffort | null, model_reasoning_summary?: ReasoningSummary | null, model_reasoning_summary_format?: ReasoningSummaryFormat | null, profile?: string | null, base_instructions?: string | null, include_apply_patch_tool?: boolean | null, model_provider?: string | null, compact_prompt?: string | null, developer_instructions?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type SandboxMode = "auto" | "read-only" | "workspace-write" | "danger-full-access";

export type AskForApproval = "unless-trusted" | "on-failure" | "on-request" | "never";

export type ReasoningEffort = "low" | "medium" | "high" | "xhigh";

export type ReasoningSummary = "auto" | "concise" | "detailed" | "none";

export type ReasoningSummaryFormat = "none" | "experimental";

export type CursorAgent = { append_prompt: AppendPrompt, force?: boolean | null, model?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Copilot = { append_prompt: AppendPrompt, model?: string | null, allow_all_tools?: boolean | null, allow_tool?: string | null, deny_tool?: string | null, add_dir?: Array<string> | null, disable_mcp_server?: Array<string> | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Opencode = { append_prompt: AppendPrompt, model?: string | null, variant?: string | null, agent?: string | null, 
/**
 * Auto-approve agent actions
 */
auto_approve: boolean, 
/**
 * Enable auto-compaction when the context length approaches the model's context window limit
 */
auto_compact: boolean, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type OpenTeamsCli = { append_prompt: AppendPrompt, model?: string | null, variant?: string | null, agent?: string | null, 
/**
 * Auto-approve agent actions
 */
auto_approve: boolean, 
/**
 * Enable auto-compaction when the context length approaches the model's context window limit
 */
auto_compact: boolean, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type QwenCode = { append_prompt: AppendPrompt, model?: string | null, thinking_effort?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Droid = { append_prompt: AppendPrompt, autonomy: Autonomy, model?: string | null, reasoning_effort?: DroidReasoningEffort | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type KimiCode = { append_prompt: AppendPrompt, model?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Autonomy = "normal" | "low" | "medium" | "high" | "skip-permissions-unsafe";

export type DroidReasoningEffort = "none" | "dynamic" | "off" | "low" | "medium" | "high";

export type AppendPrompt = string | null;

export type CodingAgentInitialRequest = { prompt: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, };

export type CodingAgentFollowUpRequest = { prompt: string, session_id: string, reset_to_message_id: string | null, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, };

export type ReviewRequest = { executor_profile_id: ExecutorProfileId, context: Array<RepoReviewContext> | null, prompt: string, 
/**
 * Optional session ID to resume an existing session
 */
session_id: string | null, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 */
working_dir: string | null, };

export type RepoReviewContext = { repo_id: string, repo_name: string, base_commit: string, };

export type CommandExitStatus = { "type": "exit_code", code: number, } | { "type": "success", success: boolean, };

export type CommandRunResult = { exit_status: CommandExitStatus | null, output: string | null, };

export type NormalizedEntry = { timestamp: string | null, entry_type: NormalizedEntryType, content: string, };

export type NormalizedEntryType = { "type": "user_message" } | { "type": "user_feedback", denied_tool: string, } | { "type": "assistant_message" } | { "type": "tool_use", tool_name: string, action_type: ActionType, status: ToolStatus, } | { "type": "system_message" } | { "type": "error_message", error_type: NormalizedEntryError, } | { "type": "thinking" } | { "type": "loading" } | { "type": "next_action", failed: boolean, execution_processes: number, needs_setup: boolean, } | { "type": "token_usage_info" } & TokenUsageInfo;

export type TokenUsageInfo = { 
/**
 * Billable tokens: input + output (cache_read excluded, it's billed at ~1/10 rate)
 */
total_tokens: number, model_context_window: number, input_tokens: number | null, output_tokens: number | null, reasoning_output_tokens: number | null, 
/**
 * Tokens served from cache (Claude: cache_read_input_tokens, Codex: cached_input_tokens)
 */
cache_read_tokens: number | null, runtime_agent: string | null, runtime_model_id: string | null, provider_id: string | null, runtime_thread_id: string | null, usage_scope: string | null, snapshot_total_tokens: number | null, snapshot_input_tokens: number | null, snapshot_output_tokens: number | null, snapshot_reasoning_output_tokens: number | null, snapshot_cache_read_tokens: number | null, is_estimated: boolean, };

export type FileChange = { "action": "write", content: string, } | { "action": "delete" } | { "action": "rename", new_path: string, } | { "action": "edit", 
/**
 * Unified diff containing file header and hunks.
 */
unified_diff: string, 
/**
 * Whether line number in the hunks are reliable.
 */
has_line_numbers: boolean, };

export type ActionType = { "action": "file_read", path: string, } | { "action": "file_edit", path: string, changes: Array<FileChange>, } | { "action": "command_run", command: string, result: CommandRunResult | null, } | { "action": "search", query: string, } | { "action": "web_fetch", url: string, } | { "action": "tool", tool_name: string, arguments: JsonValue | null, result: ToolResult | null, } | { "action": "task_create", description: string, subagent_type: string | null, result: ToolResult | null, } | { "action": "plan_presentation", plan: string, } | { "action": "todo_management", todos: Array<TodoItem>, operation: string, } | { "action": "other", description: string, };

export type TodoItem = { content: string, status: string, priority: string | null, };

export type NormalizedEntryError = { "type": "setup_required" } | { "type": "quota_exceeded", provider: string | null, } | { "type": "rate_limit_exceeded", provider: string | null, } | { "type": "server_overloaded", provider: string | null, } | { "type": "authentication_failed", provider: string | null, } | { "type": "context_limit_exceeded", provider: string | null, } | { "type": "other" };

export type ToolResult = { type: ToolResultValueType, 
/**
 * For Markdown, this will be a JSON string; for JSON, a structured value
 */
value: JsonValue, };

export type ToolResultValueType = { "type": "markdown" } | { "type": "json" };

export type ToolStatus = { "status": "created" } | { "status": "success" } | { "status": "failed" } | { "status": "denied", reason: string | null, } | { "status": "pending_approval", approval_id: string, requested_at: string, timeout_at: string, } | { "status": "timed_out" };

export type PatchType = { "type": "NORMALIZED_ENTRY", "content": NormalizedEntry } | { "type": "STDOUT", "content": string } | { "type": "STDERR", "content": string } | { "type": "DIFF", "content": Diff };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export const DEFAULT_PR_DESCRIPTION_PROMPT = "Update the PR that was just created with a better title and description.\nThe PR number is #{pr_number} and the URL is {pr_url}.\n\nAnalyze the changes in this branch and write:\n1. A concise, descriptive title that summarizes the changes, postfixed with \"(openteams)\"\n2. A detailed description that explains:\n   - What changes were made\n   - Why they were made (based on the task context)\n   - Any important implementation details\n   - At the end, include a note: \"This PR was written using [openteams](https://openteams.com)\"\n\nUse the appropriate CLI tool to update the PR (gh pr edit for GitHub, az repos pr update for Azure DevOps).";

export const DEFAULT_COMMIT_REMINDER_PROMPT = "There are uncommitted changes. Please stage and commit them now with a descriptive commit message.";